### ISSUE TITLE
Check if querySelectorAll is supported

### ISSUE THREAD

**Issue by marcospassos** [croct-tech/plug-js#79]
## ✨ Feature request

As `querySelectorAll` is still not supported by all browsers, checking if the method is available to ensure the library will not break on initialization.

**Comment by denis-rossati** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll#browser_compatibility), querySelectorAll has full suport from all modern browsers. I believe we should close this issue.

**Comment by marcospassos** [comment]
Agreed!
